### ISSUE TITLE
Command Pattern: DBbookManager as Receiver

### ISSUE THREAD

**Issue by NanyiWang** [CSC207-UofT/course-project-ask-the-magic-conch-shell#29]
We may want to modify the methods in DBbookManager since if we use it as Receiver in command pattern, the command should be able to execute an action directly with no arguments after its creation, as well the action should be public void.

**Comment by NanyiWang** [comment]
DBbookManager: Need to implement 2 methods
DBUserManager: Need to implement 2 methods
--- @ Miley

**Comment by Mileyz023** [comment]
OK. will implement them later

**Comment by Mileyz023** [comment]
I have made corrections for the implementation of the **command design pattern** by combining add & delete order into one order class and let the loginusermananger use case to execute it. The execution would involve judging whether the book status is unlended. if yes, check the student's credit score and return whether the borrow of this book is successful or not.
