### ISSUE TITLE
We shouldn't call entity constructor in controller?

### ISSUE THREAD

**Issue by nzhou27** [CSC207-UofT/course-project-ask-the-magic-conch-shell#32]
I believe we should not call the entity constructor in controller. However, I am currently working on the create new user page.  
 IDBUserManager's create new user method has a parameter Student/Staff. This force me to call this student constructor in controller with no other choice. Can someone change that please? thanks

**Comment by Mileyz023** [comment]
I found something related to this question on piazza (https://piazza.com/class/kt4hlydpsym1bz?cid=900).

**Comment by Mileyz023** [comment]
I have created two new methods in our userloginmanager use case that are able to create new student and staff entity using them.

**Comment by nzhou27** [comment]
thanks, that helped!
